### PR TITLE
Allow manual configuration for networking in nixos module

### PR DESCRIPTION
**Pull request by Mateiadrielrafael**
I added a tiny option to disable the automatic nginx and firewall configuration

### CODE REVIEW

**Comment by NorfairKing** [comment]
@Mateiadrielrafael You can already not have the hosts defined by not defining any hosts.
So I suggest we rename this to [`openFirewall`](https://search.nixos.org/options?channel=23.11&from=0&size=50&sort=relevance&type=packages&query=openFirewall) and only have it control the firewall.
What do you think?

**Comment by Mateiadrielrafael** [comment]
@NorfairKing Ah, I saw the host being passed to `api-server-config` and thought it might be used for other stuff internally. I'll change the name in a sec

**Comment by Mateiadrielrafael** [comment]
@NorfairKing Changed the name. Tried running this new version without setting the hosts (as you suggested), and it's all working fine!

**Comment by NorfairKing** [comment]
@Mateiadrielrafael Is it important to you to have a single `openFirewall`?
If not then I'll separate them into one for the api server and one for the web server, and then merge.

**Comment by Mateiadrielrafael** [comment]
@NorfairKing That's totally fine!

**Comment by Mateiadrielrafael** [comment]
yep, that's totally fine!

(Github was displaying my message twice, so I thought it got sent twice for some reason. I deleted one of them, but surprise-surprise: both got deleted, hence me resending it now:))

**Comment by NorfairKing** [comment]
Merged manually in `371f8fd`.
Will merge to master once CI passes.

**Pull request closed without merging**
